---
- hosts: all
  gather_facts: false
  become: true
  become_user: root

  pre_tasks:
  - name: install python and deps for ansible modules
    raw: dnf install -y python2 python2-dnf libselinux-python

  - name: gather facts
    setup:

  - name: use facts
    lineinfile: dest=/etc/some-cfg-file line="myip={{ ansible_eth0.ipv4.address }}" create=true

  roles:
    - iris

